kind: pipeline
name: build and publish
steps:

  - name: rootfs 
    image: archlinux/archlinux
    commands: 
      - yes|pacman -Sy base-devel
      - pacman-key --recv-keys DA6BDDD08D26A04AAC997968C79769BC07914012
      - ./build.sh
  - name: docker
    image: plugins/docker
    settings:
      repo: archxlinux/archxlinux
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
