kind: pipeline
name: build and publish
steps:
  - name: build
    image: archxlinux/builder-docker:0.1
    pull: always
    privileged: true
    commands:
      - bash /entrypoint.sh
    volumes:
    - name: build
      path: /tmp/build 
    - name: iso
      path: /tmp/iso 
  - name: login
    image: ghcr.io/supportpal/github-gh-cli 
    commands: 
      - gh auth login --with-token < $GITHUB_TOKEN

  - name: docker
    image: plugins/docker
    settings:
      repo: archxlinux/archxlinux
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
